/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/public/site": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Site */
        get: operations["site_api_v1_public_site_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/public/home": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Home */
        get: operations["home_api_v1_public_home_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/public/services": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Services */
        get: operations["services_api_v1_public_services_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/public/services/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Service */
        get: operations["service_api_v1_public_services__slug__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/public/team": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Team */
        get: operations["team_api_v1_public_team_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/public/team/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Member */
        get: operations["member_api_v1_public_team__slug__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/public/portfolio": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Portfolio */
        get: operations["portfolio_api_v1_public_portfolio_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/public/portfolio/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Piece */
        get: operations["piece_api_v1_public_portfolio__slug__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/public/portfolio/{slug}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Event */
        post: operations["event_api_v1_public_portfolio__slug__events_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/public/testimonials": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Testimonials */
        get: operations["testimonials_api_v1_public_testimonials_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/public/faqs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Faqs */
        get: operations["faqs_api_v1_public_faqs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/public/links": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Links */
        get: operations["links_api_v1_public_links_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/public/legal/privacy": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Privacy */
        get: operations["privacy_api_v1_public_legal_privacy_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/public/leads": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Lead */
        post: operations["lead_api_v1_public_leads_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/public/leads/uploads": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload */
        post: operations["upload_api_v1_public_leads_uploads_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AudioOut */
        AudioOut: {
            /** Duration S */
            duration_s: number | null;
            /** Lufs */
            lufs: number | null;
            /** M4A Url */
            m4a_url: string | null;
            /** Mp3 Url */
            mp3_url: string | null;
            /** Peaks Url */
            peaks_url: string | null;
        };
        /** BioLinkOut */
        BioLinkOut: {
            /** Id */
            id: string;
            /** Label */
            label: string;
            /** Url */
            url: string;
            /** Icon */
            icon: string;
            /** Highlight */
            highlight: boolean;
            /** Is Internal */
            is_internal: boolean;
        };
        /** BrandSettings */
        BrandSettings: {
            /** Name */
            name: string;
            /** Tagline */
            tagline: string;
            /** Logo Media Id */
            logo_media_id?: string | null;
            /** Logo Alt Media Id */
            logo_alt_media_id?: string | null;
        };
        /** ContactPublic */
        ContactPublic: {
            /** Eyebrow */
            eyebrow: string;
            /** Title */
            title: string;
            /** Email */
            email: string;
            /**
             * Whatsapp E164
             * @default
             */
            whatsapp_e164: string;
            /**
             * Whatsapp Default Msg
             * @default
             */
            whatsapp_default_msg: string;
            /** Consent Text */
            consent_text: string;
        };
        /** CreditOut */
        CreditOut: {
            /** Portfolio Slug */
            portfolio_slug: string;
            /** Portfolio Title */
            portfolio_title: string;
            /** Role Label */
            role_label: string;
        };
        /** FaqOut */
        FaqOut: {
            /** Question */
            question: string;
            /** Answer */
            answer: string;
            /** Service Slug */
            service_slug: string | null;
        };
        /** FeatureSettings */
        FeatureSettings: {
            /**
             * Ab Player
             * @default false
             */
            ab_player: boolean;
            /**
             * Testimonials
             * @default false
             */
            testimonials: boolean;
            /**
             * Turnstile
             * @default false
             */
            turnstile: boolean;
            /**
             * Whatsapp Float
             * @default false
             */
            whatsapp_float: boolean;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HeroSettings */
        HeroSettings: {
            /** Quote */
            quote: string;
            /** Title Html */
            title_html: string;
            /** Cta Primary Text */
            cta_primary_text: string;
            /** Cta Secondary Text */
            cta_secondary_text: string;
            /** Image Media Id */
            image_media_id?: string | null;
        };
        /** HomeOut */
        HomeOut: {
            site: components["schemas"]["SitePublic"];
            /** Services */
            services: components["schemas"]["ServiceCardOut"][];
            /** Team */
            team: components["schemas"]["TeamCardOut"][];
            /** Portfolio */
            portfolio: components["schemas"]["PortfolioCardOut"][];
            /** Ab Comparisons */
            ab_comparisons: components["schemas"]["PortfolioCardOut"][];
            /** Testimonials */
            testimonials: components["schemas"]["TestimonialOut"][];
        };
        /** ImageOut */
        ImageOut: {
            /** Alt */
            alt: string | null;
            /** Width */
            width: number | null;
            /** Height */
            height: number | null;
            /** Lqip */
            lqip: string | null;
            /** Webp */
            webp: {
                [key: string]: string;
            };
            /** Avif */
            avif: {
                [key: string]: string;
            };
        };
        /** LeadCreated */
        LeadCreated: {
            /**
             * Ok
             * @default true
             */
            ok: boolean;
        };
        /** LeadIn */
        LeadIn: {
            /** Name */
            name: string;
            /** Email */
            email?: string | null;
            /** Phone */
            phone?: string | null;
            /** Service Slug */
            service_slug?: string | null;
            /** Message */
            message: string;
            /** Demo Url */
            demo_url?: string | null;
            /** Demo Upload Token */
            demo_upload_token?: string | null;
            /** Tentative Date */
            tentative_date?: string | null;
            /** Consent */
            consent: boolean;
            /** Source Page */
            source_page: string;
            /** Referrer */
            referrer?: string | null;
            utm?: components["schemas"]["UtmIn"] | null;
            /**
             * Website
             * @default
             */
            website: string;
            /** Turnstile Token */
            turnstile_token?: string | null;
        };
        /** LegalSettings */
        LegalSettings: {
            /** Privacy Html */
            privacy_html: string;
            /** Privacy Updated At */
            privacy_updated_at: string;
        };
        /** PlayEventIn */
        PlayEventIn: {
            /**
             * Event
             * @enum {string}
             */
            event: "play" | "ab_toggle" | "complete";
        };
        /** PortfolioCardOut */
        PortfolioCardOut: {
            /** Slug */
            slug: string;
            /** Title */
            title: string;
            /** Artist Name */
            artist_name: string;
            /** Year */
            year: number | null;
            /** Genre */
            genre: string | null;
            /** Kind */
            kind: string;
            /** External Url */
            external_url: string | null;
            /** External Id */
            external_id: string | null;
            /** Youtube Start S */
            youtube_start_s: number | null;
            /** Is Featured */
            is_featured: boolean;
            /** Is Ab Featured */
            is_ab_featured: boolean;
            /** Play Count */
            play_count: number;
            cover: components["schemas"]["ImageOut"] | null;
            audio?: components["schemas"]["AudioOut"] | null;
            audio_before?: components["schemas"]["AudioOut"] | null;
            /** Service Slugs */
            service_slugs: string[];
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** PortfolioDetailOut */
        PortfolioDetailOut: {
            /** Slug */
            slug: string;
            /** Title */
            title: string;
            /** Artist Name */
            artist_name: string;
            /** Year */
            year: number | null;
            /** Genre */
            genre: string | null;
            /** Kind */
            kind: string;
            /** External Url */
            external_url: string | null;
            /** External Id */
            external_id: string | null;
            /** Youtube Start S */
            youtube_start_s: number | null;
            /** Is Featured */
            is_featured: boolean;
            /** Is Ab Featured */
            is_ab_featured: boolean;
            /** Play Count */
            play_count: number;
            cover: components["schemas"]["ImageOut"] | null;
            audio?: components["schemas"]["AudioOut"] | null;
            audio_before?: components["schemas"]["AudioOut"] | null;
            /** Service Slugs */
            service_slugs: string[];
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Credits Text */
            credits_text: string;
            /** Description */
            description: string | null;
        };
        /** PortfolioSettings */
        PortfolioSettings: {
            /** Eyebrow */
            eyebrow: string;
            /** Title */
            title: string;
            /** Note */
            note: string;
            /**
             * Featured Limit
             * @default 4
             */
            featured_limit: number;
        };
        /** PrivacyOut */
        PrivacyOut: {
            /** Html */
            html: string;
            /** Updated At */
            updated_at: string;
        };
        /** SectionHeading */
        SectionHeading: {
            /** Eyebrow */
            eyebrow: string;
            /** Title */
            title: string;
        };
        /** SeoSettings */
        SeoSettings: {
            /** Default Title */
            default_title: string;
            /** Title Template */
            title_template: string;
            /** Default Description */
            default_description: string;
            /** Og Image Media Id */
            og_image_media_id?: string | null;
        };
        /** ServiceCardOut */
        ServiceCardOut: {
            /** Slug */
            slug: string;
            /** Number Label */
            number_label: string;
            /** Title */
            title: string;
            /** Short Description */
            short_description: string;
            /** Icon */
            icon: string;
            /** Price From Mxn */
            price_from_mxn: number | null;
            /** Sort Order */
            sort_order: number;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** ServiceDetailOut */
        ServiceDetailOut: {
            /** Slug */
            slug: string;
            /** Number Label */
            number_label: string;
            /** Title */
            title: string;
            /** Short Description */
            short_description: string;
            /** Icon */
            icon: string;
            /** Price From Mxn */
            price_from_mxn: number | null;
            /** Sort Order */
            sort_order: number;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Long Description */
            long_description: string;
            /** Faqs */
            faqs: components["schemas"]["FaqOut"][];
            /** Portfolio */
            portfolio: components["schemas"]["PortfolioCardOut"][];
        };
        /** ServicesSettings */
        ServicesSettings: {
            /** Eyebrow */
            eyebrow: string;
            /** Title */
            title: string;
            /** Lede */
            lede: string;
            /** Hint */
            hint: string;
        };
        /** SitePublic */
        SitePublic: {
            brand: components["schemas"]["BrandSettings"];
            hero: components["schemas"]["HeroSettings"];
            studio: components["schemas"]["StudioSettings"];
            team: components["schemas"]["SectionHeading"];
            services: components["schemas"]["ServicesSettings"];
            portfolio: components["schemas"]["PortfolioSettings"];
            contact: components["schemas"]["ContactPublic"];
            social: components["schemas"]["SocialSettings"];
            seo: components["schemas"]["SeoSettings"];
            legal: components["schemas"]["LegalSettings"];
            features: components["schemas"]["FeatureSettings"];
            /** Media */
            media?: {
                [key: string]: components["schemas"]["ImageOut"];
            };
        };
        /** SocialSettings */
        SocialSettings: {
            /**
             * Instagram
             * @default
             */
            instagram: string;
            /**
             * Tiktok
             * @default
             */
            tiktok: string;
            /**
             * Youtube
             * @default
             */
            youtube: string;
            /**
             * Spotify
             * @default
             */
            spotify: string;
            /**
             * Facebook
             * @default
             */
            facebook: string;
            /**
             * X
             * @default
             */
            x: string;
            /**
             * Threads
             * @default
             */
            threads: string;
            /**
             * Soundcloud
             * @default
             */
            soundcloud: string;
        };
        /** StudioSettings */
        StudioSettings: {
            /** Eyebrow */
            eyebrow: string;
            /** Title */
            title: string;
            /** Body */
            body: string;
            /** Image Media Id */
            image_media_id?: string | null;
            /** Image Caption */
            image_caption: string;
        };
        /** TeamCardOut */
        TeamCardOut: {
            /** Slug */
            slug: string;
            /** Full Name */
            full_name: string;
            /** Nickname */
            nickname: string;
            /** Role Label */
            role_label: string;
            /** Bio Short */
            bio_short: string;
            photo: components["schemas"]["ImageOut"] | null;
            /** Socials */
            socials: {
                [key: string]: unknown;
            };
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** TeamDetailOut */
        TeamDetailOut: {
            /** Slug */
            slug: string;
            /** Full Name */
            full_name: string;
            /** Nickname */
            nickname: string;
            /** Role Label */
            role_label: string;
            /** Bio Short */
            bio_short: string;
            photo: components["schemas"]["ImageOut"] | null;
            /** Socials */
            socials: {
                [key: string]: unknown;
            };
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Bio Long */
            bio_long: string;
            /** Credits */
            credits: components["schemas"]["CreditOut"][];
        };
        /** TestimonialOut */
        TestimonialOut: {
            /** Quote */
            quote: string;
            /** Author Name */
            author_name: string;
            /** Author Role */
            author_role: string;
            /** Project Label */
            project_label: string;
            photo: components["schemas"]["ImageOut"] | null;
            /** Portfolio Slug */
            portfolio_slug: string | null;
        };
        /** UploadAccepted */
        UploadAccepted: {
            /** Upload Token */
            upload_token: string;
        };
        /** UtmIn */
        UtmIn: {
            /** Source */
            source?: string | null;
            /** Medium */
            medium?: string | null;
            /** Campaign */
            campaign?: string | null;
            /** Content */
            content?: string | null;
            /** Term */
            term?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    site_api_v1_public_site_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SitePublic"];
                };
            };
        };
    };
    home_api_v1_public_home_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HomeOut"];
                };
            };
        };
    };
    services_api_v1_public_services_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServiceCardOut"][];
                };
            };
        };
    };
    service_api_v1_public_services__slug__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServiceDetailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    team_api_v1_public_team_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeamCardOut"][];
                };
            };
        };
    };
    member_api_v1_public_team__slug__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeamDetailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    portfolio_api_v1_public_portfolio_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PortfolioCardOut"][];
                };
            };
        };
    };
    piece_api_v1_public_portfolio__slug__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PortfolioDetailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    event_api_v1_public_portfolio__slug__events_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlayEventIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    testimonials_api_v1_public_testimonials_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TestimonialOut"][];
                };
            };
        };
    };
    faqs_api_v1_public_faqs_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FaqOut"][];
                };
            };
        };
    };
    links_api_v1_public_links_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BioLinkOut"][];
                };
            };
        };
    };
    privacy_api_v1_public_legal_privacy_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PrivacyOut"];
                };
            };
        };
    };
    lead_api_v1_public_leads_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LeadIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LeadCreated"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_api_v1_public_leads_uploads_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadAccepted"];
                };
            };
        };
    };
}
