"""initial schema

Revision ID: 8ebb49b10598
Revises:
Create Date: 2026-09-29 22:18:38.609332

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "8ebb49b10598"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS citext")
    op.create_table(
        "bio_links",
        sa.Column("label", sa.Text(), nullable=False),
        sa.Column("url", sa.Text(), nullable=False),
        sa.Column("icon", sa.Text(), server_default="", nullable=False),
        sa.Column("is_internal", sa.Boolean(), server_default="false", nullable=False),
        sa.Column(
            "utm_overrides",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),
        sa.Column("starts_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ends_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("highlight", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("sort_order", sa.Integer(), server_default="0", nullable=False),
        sa.Column("is_published", sa.Boolean(), server_default="false", nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_bio_links")),
    )
    op.create_table(
        "jobs",
        sa.Column(
            "type",
            sa.Enum(
                "process_image",
                "process_audio",
                "send_email",
                "revalidate",
                name="job_type",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "queued",
                "running",
                "done",
                "failed",
                name="job_status",
                native_enum=False,
                length=32,
            ),
            server_default="queued",
            nullable=False,
        ),
        sa.Column("attempts", sa.Integer(), server_default="0", nullable=False),
        sa.Column(
            "run_after", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_jobs")),
    )
    op.create_index("ix_jobs_queue", "jobs", ["status", "run_after"], unique=False)
    op.create_table(
        "media_assets",
        sa.Column(
            "kind",
            sa.Enum("image", "audio", "file", name="media_kind", native_enum=False, length=32),
            nullable=False,
        ),
        sa.Column(
            "visibility",
            sa.Enum("public", "private", name="media_visibility", native_enum=False, length=32),
            nullable=False,
        ),
        sa.Column("original_filename", sa.Text(), nullable=False),
        sa.Column("mime_type", sa.Text(), nullable=False),
        sa.Column("size_bytes", sa.BigInteger(), nullable=False),
        sa.Column("storage_key", sa.Text(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "uploaded",
                "processing",
                "ready",
                "failed",
                name="media_status",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column(
            "variants", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False
        ),
        sa.Column("width", sa.Integer(), nullable=True),
        sa.Column("height", sa.Integer(), nullable=True),
        sa.Column("duration_s", sa.Numeric(precision=10, scale=3), nullable=True),
        sa.Column("lufs_integrated", sa.Numeric(precision=6, scale=2), nullable=True),
        sa.Column("peaks_key", sa.Text(), nullable=True),
        sa.Column("lqip", sa.Text(), nullable=True),
        sa.Column("alt_text", sa.Text(), nullable=True),
        sa.Column("sha256", sa.Text(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_media_assets")),
    )
    op.create_index(op.f("ix_media_assets_sha256"), "media_assets", ["sha256"], unique=False)
    op.create_table(
        "users",
        sa.Column("email", postgresql.CITEXT(), nullable=False),
        sa.Column("full_name", sa.Text(), nullable=False),
        sa.Column("password_hash", sa.Text(), nullable=False),
        sa.Column(
            "role",
            sa.Enum("admin", "superadmin", name="user_role", native_enum=False, length=32),
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("failed_logins", sa.Integer(), server_default="0", nullable=False),
        sa.Column("locked_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("email", name=op.f("uq_users_email")),
    )
    op.create_table(
        "bio_link_clicks",
        sa.Column("bio_link_id", sa.Uuid(), nullable=False),
        sa.Column("clicked_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("referrer", sa.Text(), nullable=True),
        sa.Column("user_agent_family", sa.Text(), nullable=True),
        sa.Column("country", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["bio_link_id"],
            ["bio_links.id"],
            name=op.f("fk_bio_link_clicks_bio_link_id_bio_links"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_bio_link_clicks")),
    )
    op.create_index(
        op.f("ix_bio_link_clicks_bio_link_id"), "bio_link_clicks", ["bio_link_id"], unique=False
    )
    op.create_table(
        "portfolio_items",
        sa.Column("slug", sa.Text(), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("artist_name", sa.Text(), nullable=False),
        sa.Column("year", sa.Integer(), nullable=True),
        sa.Column("genre", sa.Text(), nullable=True),
        sa.Column(
            "kind",
            sa.Enum(
                "own_audio",
                "spotify",
                "youtube",
                "soundcloud",
                "apple_music",
                "bandcamp",
                name="portfolio_kind",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("external_url", sa.Text(), nullable=True),
        sa.Column("external_id", sa.Text(), nullable=True),
        sa.Column("youtube_start_s", sa.Integer(), nullable=True),
        sa.Column("cover_media_id", sa.Uuid(), nullable=True),
        sa.Column("audio_after_media_id", sa.Uuid(), nullable=True),
        sa.Column("audio_before_media_id", sa.Uuid(), nullable=True),
        sa.Column("credits_text", sa.Text(), server_default="", nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("is_featured", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("is_ab_featured", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("play_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("sort_order", sa.Integer(), server_default="0", nullable=False),
        sa.Column("is_published", sa.Boolean(), server_default="false", nullable=False),
        sa.ForeignKeyConstraint(
            ["audio_after_media_id"],
            ["media_assets.id"],
            name=op.f("fk_portfolio_items_audio_after_media_id_media_assets"),
        ),
        sa.ForeignKeyConstraint(
            ["audio_before_media_id"],
            ["media_assets.id"],
            name=op.f("fk_portfolio_items_audio_before_media_id_media_assets"),
        ),
        sa.ForeignKeyConstraint(
            ["cover_media_id"],
            ["media_assets.id"],
            name=op.f("fk_portfolio_items_cover_media_id_media_assets"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_portfolio_items")),
        sa.UniqueConstraint("slug", name=op.f("uq_portfolio_items_slug")),
    )
    op.create_table(
        "services",
        sa.Column("slug", sa.Text(), nullable=False),
        sa.Column("number_label", sa.Text(), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("short_description", sa.Text(), nullable=False),
        sa.Column("long_description", sa.Text(), nullable=False),
        sa.Column("icon", sa.Text(), nullable=False),
        sa.Column("price_from_mxn", sa.Integer(), nullable=True),
        sa.Column("image_media_id", sa.Uuid(), nullable=True),
        sa.Column("seo_title", sa.Text(), nullable=True),
        sa.Column("seo_description", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("sort_order", sa.Integer(), server_default="0", nullable=False),
        sa.Column("is_published", sa.Boolean(), server_default="false", nullable=False),
        sa.CheckConstraint(
            "char_length(short_description) <= 180", name=op.f("ck_services_short_description_len")
        ),
        sa.ForeignKeyConstraint(
            ["image_media_id"],
            ["media_assets.id"],
            name=op.f("fk_services_image_media_id_media_assets"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_services")),
        sa.UniqueConstraint("slug", name=op.f("uq_services_slug")),
    )
    op.create_table(
        "site_settings",
        sa.Column("id", sa.Integer(), autoincrement=False, nullable=False),
        sa.Column("data", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["updated_by"], ["users.id"], name=op.f("fk_site_settings_updated_by_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_site_settings")),
    )
    op.create_table(
        "team_members",
        sa.Column("slug", sa.Text(), nullable=False),
        sa.Column("full_name", sa.Text(), nullable=False),
        sa.Column("nickname", sa.Text(), nullable=False),
        sa.Column("role_label", sa.Text(), nullable=False),
        sa.Column("bio_short", sa.Text(), nullable=False),
        sa.Column("bio_long", sa.Text(), server_default="", nullable=False),
        sa.Column("photo_media_id", sa.Uuid(), nullable=True),
        sa.Column(
            "socials", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("sort_order", sa.Integer(), server_default="0", nullable=False),
        sa.Column("is_published", sa.Boolean(), server_default="false", nullable=False),
        sa.ForeignKeyConstraint(
            ["photo_media_id"],
            ["media_assets.id"],
            name=op.f("fk_team_members_photo_media_id_media_assets"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_team_members")),
        sa.UniqueConstraint("slug", name=op.f("uq_team_members_slug")),
    )
    op.create_table(
        "faqs",
        sa.Column("question", sa.Text(), nullable=False),
        sa.Column("answer", sa.Text(), nullable=False),
        sa.Column("service_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("sort_order", sa.Integer(), server_default="0", nullable=False),
        sa.Column("is_published", sa.Boolean(), server_default="false", nullable=False),
        sa.ForeignKeyConstraint(
            ["service_id"], ["services.id"], name=op.f("fk_faqs_service_id_services")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_faqs")),
    )
    op.create_table(
        "leads",
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("email", postgresql.CITEXT(), nullable=True),
        sa.Column("phone_e164", sa.Text(), nullable=True),
        sa.Column("service_id", sa.Uuid(), nullable=True),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("demo_url", sa.Text(), nullable=True),
        sa.Column("demo_media_id", sa.Uuid(), nullable=True),
        sa.Column("tentative_date", sa.Date(), nullable=True),
        sa.Column("consent_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("consent_text_version", sa.Text(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "new",
                "contacted",
                "quoted",
                "won",
                "lost",
                name="lead_status",
                native_enum=False,
                length=32,
            ),
            server_default="new",
            nullable=False,
        ),
        sa.Column("source_page", sa.Text(), nullable=False),
        sa.Column("referrer", sa.Text(), nullable=True),
        sa.Column("utm_source", sa.Text(), nullable=True),
        sa.Column("utm_medium", sa.Text(), nullable=True),
        sa.Column("utm_campaign", sa.Text(), nullable=True),
        sa.Column("utm_content", sa.Text(), nullable=True),
        sa.Column("utm_term", sa.Text(), nullable=True),
        sa.Column("quote_payload", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("ip_hash", sa.Text(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "email IS NOT NULL OR phone_e164 IS NOT NULL", name=op.f("ck_leads_email_or_phone")
        ),
        sa.ForeignKeyConstraint(
            ["demo_media_id"], ["media_assets.id"], name=op.f("fk_leads_demo_media_id_media_assets")
        ),
        sa.ForeignKeyConstraint(
            ["service_id"], ["services.id"], name=op.f("fk_leads_service_id_services")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_leads")),
    )
    op.create_table(
        "play_events",
        sa.Column("portfolio_item_id", sa.Uuid(), nullable=False),
        sa.Column(
            "event",
            sa.Enum(
                "play",
                "ab_toggle",
                "complete",
                name="play_event_type",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("occurred_on", sa.Date(), nullable=False),
        sa.Column("count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["portfolio_item_id"],
            ["portfolio_items.id"],
            name=op.f("fk_play_events_portfolio_item_id_portfolio_items"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_play_events")),
        sa.UniqueConstraint(
            "portfolio_item_id", "event", "occurred_on", name="uq_play_events_daily"
        ),
    )
    op.create_table(
        "portfolio_item_credits",
        sa.Column("portfolio_item_id", sa.Uuid(), nullable=False),
        sa.Column("team_member_id", sa.Uuid(), nullable=False),
        sa.Column("role_label", sa.Text(), server_default="", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["portfolio_item_id"],
            ["portfolio_items.id"],
            name=op.f("fk_portfolio_item_credits_portfolio_item_id_portfolio_items"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["team_member_id"],
            ["team_members.id"],
            name=op.f("fk_portfolio_item_credits_team_member_id_team_members"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "portfolio_item_id", "team_member_id", name=op.f("pk_portfolio_item_credits")
        ),
    )
    op.create_table(
        "portfolio_item_services",
        sa.Column("portfolio_item_id", sa.Uuid(), nullable=False),
        sa.Column("service_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["portfolio_item_id"],
            ["portfolio_items.id"],
            name=op.f("fk_portfolio_item_services_portfolio_item_id_portfolio_items"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["service_id"],
            ["services.id"],
            name=op.f("fk_portfolio_item_services_service_id_services"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "portfolio_item_id", "service_id", name=op.f("pk_portfolio_item_services")
        ),
    )
    op.create_table(
        "testimonials",
        sa.Column("quote", sa.Text(), nullable=False),
        sa.Column("author_name", sa.Text(), nullable=False),
        sa.Column("author_role", sa.Text(), server_default="", nullable=False),
        sa.Column("project_label", sa.Text(), server_default="", nullable=False),
        sa.Column("photo_media_id", sa.Uuid(), nullable=True),
        sa.Column("portfolio_item_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("sort_order", sa.Integer(), server_default="0", nullable=False),
        sa.Column("is_published", sa.Boolean(), server_default="false", nullable=False),
        sa.ForeignKeyConstraint(
            ["photo_media_id"],
            ["media_assets.id"],
            name=op.f("fk_testimonials_photo_media_id_media_assets"),
        ),
        sa.ForeignKeyConstraint(
            ["portfolio_item_id"],
            ["portfolio_items.id"],
            name=op.f("fk_testimonials_portfolio_item_id_portfolio_items"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_testimonials")),
    )
    op.create_table(
        "lead_events",
        sa.Column("lead_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=True),
        sa.Column(
            "type",
            sa.Enum(
                "status_change",
                "note",
                "email_sent",
                name="lead_event_type",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column(
            "from_status",
            sa.Enum(
                "new",
                "contacted",
                "quoted",
                "won",
                "lost",
                name="lead_status",
                native_enum=False,
                length=32,
            ),
            nullable=True,
        ),
        sa.Column(
            "to_status",
            sa.Enum(
                "new",
                "contacted",
                "quoted",
                "won",
                "lost",
                name="lead_status",
                native_enum=False,
                length=32,
            ),
            nullable=True,
        ),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["lead_id"], ["leads.id"], name=op.f("fk_lead_events_lead_id_leads"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_lead_events_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_lead_events")),
    )
    op.create_index(op.f("ix_lead_events_lead_id"), "lead_events", ["lead_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_lead_events_lead_id"), table_name="lead_events")
    op.drop_table("lead_events")
    op.drop_table("testimonials")
    op.drop_table("portfolio_item_services")
    op.drop_table("portfolio_item_credits")
    op.drop_table("play_events")
    op.drop_table("leads")
    op.drop_table("faqs")
    op.drop_table("team_members")
    op.drop_table("site_settings")
    op.drop_table("services")
    op.drop_table("portfolio_items")
    op.drop_index(op.f("ix_bio_link_clicks_bio_link_id"), table_name="bio_link_clicks")
    op.drop_table("bio_link_clicks")
    op.drop_table("users")
    op.drop_index(op.f("ix_media_assets_sha256"), table_name="media_assets")
    op.drop_table("media_assets")
    op.drop_index("ix_jobs_queue", table_name="jobs")
    op.drop_table("jobs")
    op.drop_table("bio_links")
    op.execute("DROP EXTENSION IF EXISTS citext")
    # ### end Alembic commands ###
